version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-typescript"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hav7akajf7im"
s3_prefix = "test-typescript"
region = "us-east-1"
profile = "dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
